<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>

    <InvariantGlobalization>false</InvariantGlobalization>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <GenerateClickOnceManifests>false</GenerateClickOnceManifests>
    <GenerateManifests>false</GenerateManifests>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <SignAssembly>False</SignAssembly>
    <ErrorReport>none</ErrorReport>
    <StartupObject></StartupObject>
    <ApplicationIcon>extra\Myra.ico</ApplicationIcon>
    <PackageIcon>Myra.png</PackageIcon>
    <dpiAware>true/pm</dpiAware>
    <dpiAwareness>PerMonitorV2</dpiAwareness>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <WarningLevel>9999</WarningLevel>
    <NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
    <WarningLevel>9999</WarningLevel>
    <NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <WarningLevel>9999</WarningLevel>
    <NoWarn />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>full</DebugType>
    <WarningLevel>9999</WarningLevel>
    <NoWarn />
  </PropertyGroup>

  <ItemGroup>
    <Content Include="extra\Myra.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
  </ItemGroup>

  <ItemGroup>
    <None Update="extra\Myra.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>